# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'iOSBasicDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSBasicDemo
 pod 'Masonry', '~> 1.1.0'
 
 pod 'DSTBaseDevUtils', :git => 'git@github.com:iOSDevelopShareTeam/DSTBaseDevUtils.git', :branch => 'master'

end
